
version: "3"

services:
    rif-scheduler-services:
        image: rif-scheduler-services
        build:
            context: .
            dockerfile: Dockerfile
        env_file: .env.prod
        volumes:
            - ./storage:/app/storage
        networks:
            - rif-scheduler-services-net

networks:
    rif-scheduler-services-net:
        driver: bridge